#pragma once

#include <stdint.h>
#include <stddef.h>

// Matches ChannelDetails::name, which is what an entry is copied into.
#define CHANNEL_CONFIG_NAME_LEN     32

// 128 bits, and not by accident: CMD_GET_CHANNEL and CMD_SET_CHANNEL carry 16 bytes of
// channel secret, so a channel wider than this is one the companion app cannot read back
// or write. The build refuses a 256-bit key rather than handing the device a channel it
// could only half describe. The remaining 16 bytes of GroupChannel::secret stay zero,
// which is how setChannel() knows to hash 16 bytes rather than 32.
#define CHANNEL_CONFIG_SECRET_LEN   16

struct ChannelConfigEntry {
  char    name[CHANNEL_CONFIG_NAME_LEN];
  uint8_t secret[CHANNEL_CONFIG_SECRET_LEN];
};

/**
 * \brief  The group channels compiled into a build, as the AUTO_CHANNELS string.
 *
 * A node arrives on its network's channels without anyone pasting PSKs into the app.
 * The names come from the network profile and the keys from a key file that is not
 * committed; the Makefile joins them and hands the firmware the result, so nothing here
 * has to know about either file.
 *
 * Wire format, one flag, no spaces so it survives a build-flag environment intact:
 *
 *     name:32_hex_chars,name:32_hex_chars
 *
 * Resolving happens in the build, not here: a key written as a passphrase or a base64
 * PSK has already been reduced to hex by then. This end only reads hex, which is why it
 * needs no crypto, no allocation and no Arduino - and can be tested off-device.
 *
 * Pure logic, so the whole of it is one static function.
 */
class ChannelConfig {
public:
  /**
   * \brief  Parse the AUTO_CHANNELS string.
   * \param  dest         filled oldest-first, in the order the names were given.
   * \param  max_entries  capacity of 'dest'; parsing stops once it is full.
   * \returns  how many entries were stored, or -1 if the string is malformed.
   *
   * Malformed is all-or-nothing on purpose. The string is generated by the build, so a
   * bad one means the generator is wrong rather than one channel being off - and half a
   * channel list is a worse thing to put on a device than none, because it looks right.
   */
  static int parse(const char* spec, ChannelConfigEntry* dest, int max_entries);
};
